### ISSUE TITLE
Need to move Andy's documentation to an NCAS location

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/cf-view#18]
And move all the links in the various setup, readme, etc code.

**Comment by sadielbartholomew** [comment]
Hi @bnlawrence, thanks for raising this. I agree! I was due to start compiling issues for cf-view (of which this would be one the first as most urgent) though I am still trying to work through some major work towards getting cf-plot in a state I'd feel comfortable developing on (e.g. code standards, modularisation and getting the docs hosted centrally via NCAS-CMS, likewise there). But I should show cf-view some love too at this stage!

Andy provided a tarball of cf-view docs, so I can start work on that next week (I'm at a workshop today until Thursday inclusive so not much time this week). Hope that timeline sounds OK.
